import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TasksProvider } from "./hooks/useTasks";
import { AuthProvider } from "./contexts/AuthContext";
import { AuthModalProvider } from "./hooks/useAuthModal";
import { HolidaysProvider } from "./providers/HolidaysProvider";
import { ToastProvider } from "./contexts/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <AuthProvider>
            <AuthModalProvider>
              <HolidaysProvider>
                <TasksProvider>{children}</TasksProvider>
              </HolidaysProvider>
            </AuthModalProvider>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
